### ISSUE TITLE
Not an issue :)

### ISSUE THREAD

**Issue by JFDionne** [BradKwon/Xamarin.Android.Binding.Mapbox.Android.Navigation.UI#1]
Thank you very much for share new version !

any chance you do the iOS version? :)

**Comment by BradKwon** [comment]
Hi @JFDionne. Unfortunately, I have not learned iOS but Android. Once I could develop iOS, then there would be a chance to bind the iOS version. In the meantime, you can try this [NAXAM's binding](https://github.com/NAXAM/mapboxnavigation-ios-binding) 😄
