### ISSUE TITLE
Java exited with error 2

### ISSUE THREAD

**Issue by JacquesOkes** [BradKwon/Xamarin.Android.Binding.Mapbox.Android.Navigation.UI#2]
Hi, Java exited with code 2 error on build. Multi-Dex is on.

I added references one by one and found the error code comes in when adding Square.OkIO

Any ideas? I am adding it to my existing App as I want the integrated navigation in my application as I need control of specific routes etc

Please could you assist. Thanks very much for all of this!

**Comment by BradKwon** [comment]
Hey @JacquesOkes , I am planning to update this Mapbox binding. But beforehand, let's make yours run first :)
